apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: todos-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              value: myfancysecret
            - name: REDIS_CHANNEL
              value: log_channel
            - name: REDIS_HOST
              value: redis-queue
            - name: REDIS_PORT
              value: "6379"
            - name: TODO_API_PORT
              value: "8082"
            - name: ZIPKIN_URL
              value: http://zipkin:9411/api/v2/spans
          image: mvg1k/todos-api
          name: todos-api
      restartPolicy: Always
