apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: AUTH_API_ADDRESS
              value: http://auth-api:8081
            - name: PORT
              value: "8080"
            - name: TODOS_API_ADDRESS
              value: http://todos-api:8082
            - name: ZIPKIN_URL
              value: http://zipkin:9411/api/v2/spans
          image: mvg1k/frontend
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
