apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: redis-queue
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: redis-queue
  template:
    metadata:
      labels:
        app: redis-queue
    spec:
      containers:
        - image: redis
          name: redis-queue
      restartPolicy: Always
